image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: localhost:5000/my-flask-app

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .

push:
  stage: push
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN localhost:5000
    - docker push $IMAGE_NAME
